//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Lisanslı Apache Lisansı, Sürüm 2.0 (the "License") altında
bu dosyayı yalnızca Lisans'a uygun olarak kullanabilirsiniz.
Lisansın bir kopyasını aşağıdaki adresten edinebilirsiniz:

	http://www.apache.org/licenses/LICENSE-2.0

Yürürlükteki yasa veya yazılı izin gereği aksi belirtilmedikçe,
bu yazılım Lisans kapsamında "OLDUĞU GİBİ" dağıtılmakta,
HERHANGİ BİR GARANTİ VERİLMEMEKTEDİR.
Lisans kapsamındaki izinler ve sınırlamalar hakkında daha fazla bilgi için Lisansı inceleyin.
*/

// controller-gen object tarafından otomatik oluşturulmuştur, elle değiştirmeyin

package v3

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto, alıcıyı kopyalayan ve out'a yazan otomatik oluşturulmuş bir deepcopy fonksiyonudur. in boş olmamalıdır.
func (in *ExternalJob) DeepCopyInto(out *ExternalJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy, alıcıyı kopyalayan ve yeni bir ExternalJob oluşturan otomatik oluşturulmuş bir deepcopy fonksiyonudur.
func (in *ExternalJob) DeepCopy() *ExternalJob {
	if in == nil {
		return nil
	}
	out := new(ExternalJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject, alıcıyı kopyalayan ve yeni bir runtime.Object oluşturan otomatik oluşturulmuş bir deepcopy fonksiyonudur.
func (in *ExternalJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto, alıcıyı kopyalayan ve out'a yazan otomatik oluşturulmuş bir deepcopy fonksiyonudur. in boş olmamalıdır.
func (in *ExternalJobList) DeepCopyInto(out *ExternalJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExternalJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy, alıcıyı kopyalayan ve yeni bir ExternalJobList oluşturan otomatik oluşturulmuş bir deepcopy fonksiyonudur.
func (in *ExternalJobList) DeepCopy() *ExternalJobList {
	if in == nil {
		return nil
	}
	out := new(ExternalJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject, alıcıyı kopyalayan ve yeni bir runtime.Object oluşturan otomatik oluşturulmuş bir deepcopy fonksiyonudur.
func (in *ExternalJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto, alıcıyı kopyalayan ve out'a yazan otomatik oluşturulmuş bir deepcopy fonksiyonudur. in boş olmamalıdır.
func (in *ExternalJobSpec) DeepCopyInto(out *ExternalJobSpec) {
	*out = *in
}

// DeepCopy, alıcıyı kopyalayan ve yeni bir ExternalJobSpec oluşturan otomatik oluşturulmuş bir deepcopy fonksiyonudur.
func (in *ExternalJobSpec) DeepCopy() *ExternalJobSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto, alıcıyı kopyalayan ve out'a yazan otomatik oluşturulmuş bir deepcopy fonksiyonudur. in boş olmamalıdır.
func (in *ExternalJobStatus) DeepCopyInto(out *ExternalJobStatus) {
	*out = *in
}

// DeepCopy, alıcıyı kopyalayan ve yeni bir ExternalJobStatus oluşturan otomatik oluşturulmuş bir deepcopy fonksiyonudur.
func (in *ExternalJobStatus) DeepCopy() *ExternalJobStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalJobStatus)
	in.DeepCopyInto(out)
	return out
}
